### ISSUE TITLE
sent messages not arriving

### ISSUE THREAD

**Issue by SappigeSoes** [Ganapati/Simple-Game-Server#4]
Hi,

I want to use this game server for a school project, as it just seems perfect for my use case (I'm not very experienced when it comes to networking) but I've ran into a problem. When I start the server and the example client.py, it does connect and the room shows 3/3 with the list command. However, sent messages seem to just vanish. the message variable in client.py just stays at 0 and nothing is printed on the client window (after client3 joined). I'm just running server.py and client.py unmodified. Am I doing something wrong or is it just broken?

Thanks in advance

**Comment by darshil012** [comment]
I got the scripts to work correctly...but it is more than a year ago. Ill help you later today cause it is 1:23 am here. Remind me if I forget...happy to help

**Comment by SappigeSoes** [comment]
That would be great!

**Comment by SappigeSoes** [comment]
@darshil012 Here's a reminder

**Comment by darshil012** [comment]
The reminder reminded...thanks

**Comment by darshil012** [comment]
How do you want me to send you the scripts?

**Comment by SappigeSoes** [comment]
Can you zip them and attach them to a comment on this thread?

**Comment by darshil012** [comment]
In client.py
Change 
self.sock_tcp.send(message.encode())

In lines 64, 81

And line 163
return json.loads(message[0].decode('utf-8')) instead of 
return set(message)

Server.py
Line 289
self.rooms.leave()


I can share the files if you want...

**Comment by SappigeSoes** [comment]
I'm pretty sure I changed everything correctly, but it gives this error:

Traceback (most recent call last):
  File "C:\Users\myname\Documents\Simple-Game-Server-master\client.py", line 246, in <module>
    message = client1.get_messages()
  File "C:\Users\myname\Documents\Simple-Game-Server-master\client.py", line 163, in get_messages
    return json.loads(message[0].decode('utf-8'))
IndexError: list index out of range

I would appreciate it if you send the files.

**Comment by darshil012** [comment]
If you feel okay to share your email address here...ill send else mine is darshil012@gmail.com

**Comment by SappigeSoes** [comment]
I'll send you an email so you can reply to it, I prefer not to share on here.

**Comment by SappigeSoes** [comment]
Okay, so the server.py doesnt run because it misses the module "testdeck", so I removed the import testdeck line and the quotation marks around the first if __name__ == "__main__": statement, is this correct? 

I did the same thing with the if __name__ == "__main__": in client.py (they were both in quotation marks) and it runs, but still gives the same error as mentioned above. Does it work on your side?

**Comment by darshil012** [comment]
I also am a student.....dont feel stupid...everyone feels it....ill check the files...can I know how much time have you got for the submissions?

**Comment by SappigeSoes** [comment]
Thank you very much, please don't worry about the time, I still have more than a week until I have to get this working and even then I can still abandon online multiplayer and just make it local multiplayer.

If I have the ip on localhost, I definitely don't need to worry about port forwarding right? I portforwarded and tried from a different network and a completely different local network (to eliminate mine being the culprit) and it still didnt work btw. 

I also checked that self.server_message in the get_messages function stays empty, so the messages are definitely not being received. I don't know how to check if they were sent properly though. It seems only tcp functions are working, that would at least explain why you can join a room but data transmission isnt working. (I read udp is used for broadcasting data and tcp for the server actions). It could of course also be the server but that feels a bit too complicated for me to troubleshoot.

**Comment by darshil012** [comment]
Ohh I was a bit occupied....I realised I was meant to help you...did it work?

**Comment by SappigeSoes** [comment]
No problem. It didn't work yet unfortunately. According to the readme you need to run the server with the default arguments and a capacity argument to change the capacity. If I change what you said in a previous comment, it comes up with that error and the same thing for your sent files.

**Comment by darshil012** [comment]
Check out the new zip I sent you. Try to run it. It did for me

**Comment by SappigeSoes** [comment]
I'm pretty sure it works!

The client outputs this:
1235
1236
1237
1238
1239
1212
connected
connected
connected
connected
connected
{'e905f784-ada6-491e-ae6b-2a38261b2f53': '["\\u26637", "\\u2665Q", "\\u2665K", "\\u26607", "\\u2666K", "\\u2666J", "\\u2660A", "\\u26635"]', 'action': 'hand'}
{'fbdc4c57-3254-4558-8ad6-ed13c1a382e4': '["\\u26665", "\\u2660K", "\\u26608", "\\u266610", "\\u2663K", "\\u26656", "\\u266510", "\\u2666A"]', 'action': 'hand'}
{'06992813-cbc4-4adf-817c-1c86b9e72699': '["\\u26668", "\\u26603", "\\u266010", "\\u26664", "\\u26634", "\\u26604", "\\u2665J", "\\u26667"]', 'action': 'hand'}
{'327fea44-1911-44bc-bd4e-b00c95f2603f': '["\\u2666Q", "\\u26657", "\\u26663", "\\u26638", "\\u2665A", "\\u26658", "\\u26639", "\\u2663Q"]', 'action': 'hand'}
{'f57f83d7-0c9f-4767-b7b5-3041eb9ff927': '["\\u26633", "\\u26655", "\\u26609", "\\u266310", "\\u26636", "\\u26659", "\\u26669", "\\u2660Q"]', 'action': 'hand'}
{'da484859-eeed-4d9c-99dc-bd559bd7ef10': '["\\u26606", "\\u26666", "\\u26605", "\\u2663A", "\\u2660J", "\\u2663J", "\\u26654", "\\u26653"]', 'action': 'hand'}'

I assume those are the messages?

Assuming it works, how do I set it up to get the server working on its own?

**Comment by darshil012** [comment]
Check out the server.py and gameclient.py files...i mean their main functions

**Comment by SappigeSoes** [comment]
I haven't gotten it to work yet unfortunately, but I might have made some other progress in localizing the problem. To me, it seems that the run function in the Socketthread class in client.py isn't working properly. I "tracked" the messages using print commands right before they are sent from place to place. The last time it works is when they are sent to the client in player.py. Then, as far as I know, they are supposed to be picked up with the run function. I know threading is used for multitasking, but I have never used it or know much about it so I hope maybe you can help?

I tested all this:
- After being sent from client to server, the messages are sent to the receiving client.
- The initialization function in class socketthread is run 3 times, one for every client (I believe this is how its supposed to be.)
- The run function is run 3 times (I believe this is also correct.)
- The while loop in the run function is also run three times (I believe this is where it goes wrong, and that it is a problem with the threading.)

Thus, no messages are received because they are only retrieved from the socket 3 times, at the clients creation before any messages are sent. Do you happen to know how to solve this? I put the mentioned code below.

`class SocketThread(threading.Thread):
    def __init__(self, addr, client, lock):
        """
        Client udp connection
        """
        threading.Thread.__init__(self)
        self.client = client
        self.lock = lock
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        self.sock.bind(addr)

    def run(self):
        """
        Get responses from server
        """
        while True:
            data, addr = self.sock.recvfrom(1024)
            self.lock.acquire()
            try:
                self.client.server_message.append(data)
            finally:
                self.lock.release()

    def stop(self):
        """
        Stop thread
        """
        self.sock.close()`

**Comment by darshil012** [comment]
I can't see what's the problem, maybe you can modify the gameclient.py file as per your needs...sorry

**Comment by SappigeSoes** [comment]
That's alright, thanks for your help anyway. Maybe @Ganapati could help? I do believe this is an issue that breaks the server.

**Comment by SappigeSoes** [comment]
json.dumps in sendto (line35 in player.py) wasnt encoded, so thats why it didn't work. @darshil012 I dont think I would've figured it out without your help, thanks! I made a pull request to fix it (if I did it correctly).

[Simple-Game-Server.zip](https://github.com/Ganapati/Simple-Game-Server/files/6409700/Simple-Game-Server.zip)
